[[profile]]
name = "laptop"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=0x1433", "s=", "v=Chimei Innolux Corporation"]
mode = "1920x1200@60.003Hz"
position = "0,0"
scale = 1
transform = "normal"
adaptive_sync = false


[[profile]]
name = "casa"

[[profile.output]]
enable = true
search = ["m=U28E590", "s=HTPKB01189", "v=Samsung Electric Company"]
mode = "3840x2160@59.997Hz"
position = "1280,0"
scale = 1.5
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=0x1433", "s=", "v=Chimei Innolux Corporation"]
mode = "1920x1200@60.003Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = false
